version: 2

sources:
  - name: raw
    schema: gz_raw_data
    tables:
        - name: product
          identifier: raw_gz_product
          description: table source for products
        - name: sales
          identifier: raw_gz_sales
          description : table source for sales
        - name: ship
          identifier: raw_gz_ship
          description: table source for ships
