version: 2

sources:
  - name: raw
    schema: gz_raw_data
    description: greenweeze raw data
    tables:
      - name: product
        identifier: raw_gz_product
        description: products of greenweeze
        columns:
          - name: products_id
            description: Primary key of the table
            tests:
                - unique
                - not_null
          - name: products_id
            description: the id of the product
          - name: purchase_price
            description: the price of the purchase
      - name: sales
        identifier: raw_gz_sales
        description: table source for sales
        tests:
            - unique:
                column_name : "(orders_id||'-'||pdt_id)"
        freshness:
          warn_after: {count: 90, period: day}
        loaded_at_field: "CAST(date_date AS TIMESTAMP)"
        columns:
          - name: date_date
            description: the date of purchase
          - name: orders_id
            description: the id of the order
          - name: pdt_id
            description: the id of the product
          - name: revenue
            description: revenu of each product
          - name: quantity
            description: the quantity of purchase
      - name: ship
        identifier: raw_gz_ship
        description: table source for ships
        columns:
          - name: orders_id
            description: Primary key of the table
            tests:
                - unique
                - not_null
          - name: orders_id
            description: the id of the order
          - name: shipping_fee
            description: the free of shipping
          - name: logCost
            description: the cost of logistic
          - name: ship_cost
            description: the cost of the ship
